<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin Settings' => '',
    'Collapsed' => '',
    'Default' => '',
    'Disabled' => '',
    'Error removing the node. Please try again later.' => '',
    'ID' => '',
    'Icon' => '',
    'Icon Type' => '',
    'Movable Down' => '',
    'Movable Left' => '',
    'Movable Right' => '',
    'Movable Up' => '',
    'Move Down' => '',
    'Move Left' => '',
    'Move Right' => '',
    'Move Up' => '',
    'Node # {id} - \'{name}\': {error}' => '',
    'Read Only' => '',
    'Removable' => '',
    'Removable (with children)' => '',
    'Reset' => '',
    'Root' => '',
    'Select...' => '',
    'Selected' => '',
    'The selected node cannot be moved.' => '',
    'Untitled' => '',
    'Visible' => '',
    '(new)' => '(baru)',
    'Active' => 'Aktif',
    'Add new' => 'Tambah baru',
    'Add new root' => 'Tambah root baru',
    'Already at bottom-most node in the hierarchy.' => 'Node sudah dalam hirarki yang paling bawah.',
    'Already at left-most node in the hierarchy.' => 'Node sudah dalam hirarki yang paling kiri.',
    'Already at right-most node in the hierarchy.' => 'Node sudah dalam hirarki yang paling kanan.',
    'Already at top-most node in the hierarchy.' => 'Node sudah dalam hirarki yang paling atas.',
    'Are you sure you want to remove this node?' => 'Apakah anda setuju akan menghapus node ini?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Tidak bisa membuat node. Parent node tidak disimpan atau tidak valid.',
    'Cannot move this node as the node details are not saved yet.' => 'Tidak bisa memindahkan node, sebagai rincian node masih belum tersimpan.',
    'Clear search results' => 'Bersihkan hasil pencarian',
    'Delete' => 'Hapus',
    'Depth' => 'Kedalaman',
    'Error while creating the node. Please try again later.' => 'Kesalahan saat membuat node. Silakan coba lagi nanti.',
    'Error while moving the node. Please try again later.' => 'Kesalahan saat memindahkan node. Silakan coba lagi nanti.',
    'Error while removing the node. Please try again later.' => 'Kesalahan saat menghapus node. Silakan coba lagi nanti.',
    'Error while saving the node. Please try again later.' => 'Kesalahan saat menyimpan node. Silakan coba lagi nanti.',
    'Error while viewing the node. Please try again later.' => 'Kesalahan saat menampilkan node. Silakan coba lagi nanti.',
    'Left' => 'Kiri',
    'Name' => 'Nama',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Tidak ada tree node yang bisa ditampilkan. Gunakan tombol di toolbar untuk menambahkan node.',
    'Refresh' => 'Segarkan',
    'Right' => 'Kanan',
    'Save' => 'Simpan',
    'Saved the node details successfully.' => 'Berhasil menyimpan detail node',
    'Search...' => 'Cari...',
    'Select a node by clicking on one of the tree items.' => 'Pilih node dengan meng-klik salah satu tree items.',
    'The node was moved successfully.' => 'Node telah berhasil dipindahkan.',
    'The node was removed successfully.' => 'Node telah berhasil dihapus.',
    'The node was successfully created.' => 'Node telah berhasil dibuat.',
    'The untitled node was removed.' => 'Untitled node sudah dihapus.',
    'This operation is not allowed.' => 'Operasi ini tidak diperbolehkan.',
];
