<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    'Cannot create {node}. Parent node is not saved or is invalid.' => '',
    'Cannot move root level {nodes} before or after other root level {nodes}.' => '',
    'Child Allowed' => '',
    'Error removing the {node}. Please try again later.' => '',
    'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => '',
    'The selected {node} cannot be moved.' => '',
    'You cannot add children under this {node}.' => '',
    'Cannot create {node}. Parent {node} is not saved or is invalid.' => '@@{node} konnte nicht erstellt werden. Eltern {node} nicht gespeichert oder ungültig.@@',
    'No valid tree {nodes} are available for display. Use toolbar buttons to add tree {nodes}.' => '@@Keine {{nodes}} für die Anzeige. Fügen neue {{nodes}} über die Toolbar ein.@@',
    '(new)' => '(Neu)',
    'Active' => 'Aktiv',
    'Add new' => 'Neuer',
    'Add new root' => 'Neuer Root',
    'Admin Settings' => 'Administrator Einstellungen',
    'Already at bottom-most {node} in the hierarchy.' => 'Bereits am letzten {node}',
    'Already at left-most {node} in the hierarchy.' => 'Bereits am höchsten {node}',
    'Already at right-most {node} in the hierarchy.' => 'Bereits am tiefsten {node}',
    'Already at top-most {node} in the hierarchy.' => 'Bereits am obersten {node}',
    'Are you sure you want to remove this {node}?' => 'Wollen Sie diesen {node} wirklich löschen?',
    'Cannot move this {node} as the {node} details are not saved yet.' => '{node} konnte nicht verschoben werden, da die Details noch nicht gespeichert wurden.',
    'Clear search results' => 'Suchergebnis verwerfen',
    'Collapsed' => 'Eingeklappt',
    'Default' => 'Standart',
    'Delete' => 'Löschen',
    'Depth' => 'Tiefe',
    'Disabled' => 'Deaktiviert',
    'Error while creating the {node}. Please try again later.' => 'Fehler beim Erstellen des {node}. Bitte versuchen Sie es später noch einmal.',
    'Error while moving the {node}. Please try again later.' => 'Fehler beim Verschieben des {node}. Bitte versuchen Sie es später noch einmal.',
    'Error while removing the {node}. Please try again later.' => 'Fehler beim Entfernen des {node}. Bitte versuchen Sie es später noch einmal.',
    'Error while saving the {node}. Please try again later.' => 'Fehler beim Speichern der {node}. Bitte versuchen Sie es später noch einmal.',
    'Error while viewing the {node}. Please try again later.' => 'Fehler beim Anzeigen der {node}. Bitte versuchen Sie es später noch einmal.',
    'ID' => 'ID',
    'Icon' => 'Icon',
    'Icon Type' => 'Icon Typ',
    'Left' => 'Links',
    'Movable Down' => 'Nach unten verschiebbar',
    'Movable Left' => 'Nach links verschiebbar',
    'Movable Right' => 'Nach rechts verschiebbar',
    'Movable Up' => 'Nach oben verschiebbar',
    'Move Down' => 'Nach unten schieben',
    'Move Left' => 'Nach links schieben',
    'Move Right' => 'Nach rechts schieben',
    'Move Up' => 'Nach oben schieben',
    'Name' => 'Name',
    'Read Only' => 'Nur lesen',
    'Refresh' => 'Neu laden',
    'Removable' => 'Löschbar',
    'Removable (with children)' => 'Löschbar (mit enthaltenen Einträgen)',
    'Reset' => 'Zurücksetzen',
    'Right' => 'Rechts',
    'Root' => 'Stamm',
    'Save' => 'Speichern',
    'Saved the {node} details successfully.' => '{node} details erfolgreich gespeichert.',
    'Search...' => 'Suchen...',
    'Select a {node} by clicking on one of the tree items.' => 'Wähle einen der drei {node} durch klicken. ',
    'Select...' => 'Auswahl...',
    'Selected' => 'Ausgewählt',
    'The untitled {node} was removed.' => 'Der unbenannte {node} wurde erfolgreich gelöscht.',
    'The {node} was moved successfully.' => 'Der {node} wurde erfolgreich verschoben.',
    'The {node} was removed successfully.' => 'Der {node} wurde erfolgreich gelöscht.',
    'The {node} was successfully created.' => 'Der {node} wurde erfolgreich erstellt.',
    'This operation is not allowed.' => 'Aktion ist nicht erlaubt.',
    'Untitled' => 'Unbenannt',
    'Visible' => 'Sichtbar',
    'node' => 'Knoten',
    'nodes' => 'Knoten',
    '{node} # {id} - \'{name}\': {error}' => '{node} # {id} - \'{name}\': {error}',
];
