<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    '(new)' => '(nieuw)',
    'Active' => 'Actief',
    'Add new' => 'Voeg nieuwe toe',
    'Add new root' => 'Voeg nieuwe root toe',
    'Admin Settings' => 'Beheerder instellingen',
    'Already at bottom-most node in the hierarchy.' => 'Reeds bij de meest onderste node in de hiërarchie.',
    'Already at left-most node in the hierarchy.' => 'Reeds bij de meest linkse node in de hiërarchie.',
    'Already at right-most node in the hierarchy.' => 'Reeds bij de meest rechtse node in de hiërarchie.',
    'Already at top-most node in the hierarchy.' => 'Reeds bij de meest bovenste node in de hiërarchie.',
    'Are you sure you want to remove this node?' => 'Weet u zeker dat u deze node wilt verwijderen?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Kan node niet aanmaken. Ouder node is niet opgeslagen of is ongeldig.',
    'Cannot move this node as the node details are not saved yet.' => 'Kan deze node niet verplaatsen omdat de node gegevens nog niet zijn opgeslagen.',
    'Clear search results' => 'Wis zoekresultaat',
    'Collapsed' => 'Ingeklapt',
    'Default' => 'Standaard',
    'Delete' => 'Verwijder',
    'Depth' => 'Diepte',
    'Disabled' => 'Uitgeschakeld',
    'Error removing the node. Please try again later.' => 'Fout met het verwijderen van de node. Probeer het later opnieuw.',
    'Error while creating the node. Please try again later.' => 'Fout tijdens het aanmaken van de node. Probeer het later opnieuw.',
    'Error while moving the node. Please try again later.' => 'Fout tijdens het verplaatsen van de node. Probeer het later opnieuw.',
    'Error while removing the node. Please try again later.' => 'Fout tijdens het verwijderen van de node. Probeer het later opnieuw.',
    'Error while saving the node. Please try again later.' => 'Fout tijdens het opslaan van de node. Probeer het later opnieuw.',
    'Error while viewing the node. Please try again later.' => 'Fout tijdens het bekijken van de node. Probeer het later opnieuw.',
    'ID' => 'ID',
    'Icon' => 'Icoon',
    'Icon Type' => 'Icoontype',
    'Left' => 'Links',
    'Movable Down' => 'Verplaatsbaar Beneden',
    'Movable Left' => 'Verplaatsbaar Links',
    'Movable Right' => 'Verplaatsbaar Rechts',
    'Movable Up' => 'Verplaatsbaar Boven',
    'Move Down' => 'Verplaats Beneden',
    'Move Left' => 'Verplaats Links',
    'Move Right' => 'Verplaats Rechts',
    'Move Up' => 'Verplaats Boven',
    'Name' => 'Naam',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Geen geldige boom nodes beschikbaar om te tonen. Gebruik de toolbar knoppen om boom nodes toe te voegen.',
    'Node # {id} - \'{name}\': {error}' => 'Node # {id} - \'{name}\': {error}',
    'Read Only' => 'Alleen lezen',
    'Refresh' => 'Ververs',
    'Removable' => 'Verwijderbaar',
    'Removable (with children)' => 'Verwijderbaar (met kinderen)',
    'Reset' => 'Reset',
    'Right' => 'Rechts',
    'Root' => 'Root',
    'Save' => 'Opslaan',
    'Saved the node details successfully.' => 'De node gegevens zijn succesvol opgeslagen.',
    'Search...' => 'Zoeken...',
    'Select a node by clicking on one of the tree items.' => 'Selecteer een node door op een van de boom items te klikken.',
    'Select...' => 'Selecteer...',
    'Selected' => 'Geselecteerd',
    'The node was moved successfully.' => 'De node is succesvol verplaatst.',
    'The node was removed successfully.' => 'De node is succesvol verwijderd.',
    'The node was successfully created.' => 'De node is succesvol aangemaakt.',
    'The selected node cannot be moved.' => 'De geselecteerde node kan niet verplaatst worden.',
    'The untitled node was removed.' => 'De naamloze node is verwijderd.',
    'This operation is not allowed.' => 'Deze operatie is niet toegestaan.',
    'Untitled' => 'Naamloos',
    'Visible' => 'Zichtbaar',
];
