<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(new)' => '(uus)',
    'Active' => 'Aktiivne',
    'Add new' => 'Lisa uus',
    'Add new root' => 'Lisa uus tüvi',
    'Admin Settings' => 'Administraatori seaded',
    'Already at bottom-most node in the hierarchy.' => 'Juba hierarhia kõige alumise elemendi juures.',
    'Already at left-most node in the hierarchy.' => 'Juba hierarhia kõige vasakpoolsema elemendi juures.',
    'Already at right-most node in the hierarchy.' => 'Juba hierarhia kõige parempoolsema elemendi juures.',
    'Already at top-most node in the hierarchy.' => 'Juba hierarhia kõige ülemise elemendi juures.',
    'Are you sure you want to remove this node?' => 'Oled sa kindel, et tahad selle elemendi kustutada?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Ei saa elementi lisada. Ülemus-element on salvestamata või vigane.',
    'Cannot move this node as the node details are not saved yet.' => 'Ei saa seda elementi liigutada, kuna elemendi detailid ei ole veel salvestatud.',
    'Clear search results' => 'Puhasta otsingu tulemused',
    'Collapsed' => '',
    'Default' => 'Vaikimisi',
    'Delete' => 'Kustuta',
    'Depth' => 'Sügavus',
    'Disabled' => '',
    'Error removing the node. Please try again later.' => 'Viga elemendi kustutamisel. Palun proovi hiljem uuesti.',
    'Error while creating the node. Please try again later.' => 'Viga elemendi loomisel. Palun proovi hiljem uuesti.',
    'Error while moving the node. Please try again later.' => 'Viga elemendi liigutamisel. Palun proovi hiljem uuesti.',
    'Error while removing the node. Please try again later.' => 'Viga elemendi kustutamisel. Palun proovi hiljem uuesti.',
    'Error while saving the node. Please try again later.' => 'Viga elemendi salvestamisel. Palun proovi hiljem uuesti.',
    'Error while viewing the node. Please try again later.' => 'Viga elemendi vaatamisel. Palun proovi hiljem uuesti.',
    'ID' => '',
    'Icon' => 'Ikoon',
    'Icon Type' => 'Ikooni tüüp',
    'Left' => 'Vasak',
    'Movable Down' => 'Alla liigutatav',
    'Movable Left' => 'Vasakule liigutatav',
    'Movable Right' => 'Paremale liigutatav',
    'Movable Up' => 'Üles liigutatav',
    'Move Down' => 'Liigutata alla',
    'Move Left' => 'Liigutata vasakule',
    'Move Right' => 'Liigutata paremale',
    'Move Up' => 'Liigutata üles',
    'Name' => 'Nimi',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Ühtki puu elementi ei ole näitamiseks saadaval. Palun kasuta tööriba nuppe, et elemente lisada.',
    'Node # {id} - \'{name}\': {error}' => 'Element # {id} - \'{name}\': {error}',
    'Read Only' => 'Ainult lugemiseks',
    'Refresh' => 'Värskenda',
    'Removable' => 'Eemaldatav',
    'Removable (with children)' => 'Eemaldatav (koos alam-elementidega)',
    'Reset' => 'Lähtesta',
    'Right' => 'Parem',
    'Root' => 'Tüvi',
    'Save' => 'Salvesta',
    'Saved the node details successfully.' => 'Elemendi detailide salvestamine õnnestus.',
    'Search...' => 'Otsi...',
    'Select a node by clicking on one of the tree items.' => 'Valimiseks kliki mõnel puu elemendil',
    'Select...' => 'Vali...',
    'Selected' => 'Valitud',
    'The node was moved successfully.' => 'Elemendi liigutamine õnnestus.',
    'The node was removed successfully.' => 'Elemendi kustutamine õnnestus.',
    'The node was successfully created.' => 'Elemendi loomine õnnestus.',
    'The selected node cannot be moved.' => 'Valitud elementi ei saa liigutada.',
    'The untitled node was removed.' => 'Ilma nimeta element kustutati.',
    'This operation is not allowed.' => 'See toiming ei ole lubatud.',
    'Untitled' => 'Ilma nimeta',
    'Visible' => 'Nähtav',
];
