<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    'Cannot create {node}. Parent node is not saved or is invalid.' => 'Нельзя создать {node}. Родительский {node} не сохранен',
    'Cannot move root level {nodes} before or after other root level {nodes}.' => 'Движение корневых {nodes} между другими корневыми {nodes} невозможно',
    'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => 'Нет доступных {nodes} для отображения. Используйте тулбар для добавлния новых {nodes}',
    'You cannot add children under this {node}.' => 'Вы не можете добавить дочерний элемент в корневой {node} ',
    'Cannot create {node}. Parent {node} is not saved or is invalid.' => '@@Нельзя создать {node}. Родительский {node} не сохранен@@',
    'No valid tree {nodes} are available for display. Use toolbar buttons to add tree {nodes}.' => '@@Нет доступных {nodes} дерева для отображения. Используйте кнопки на панели инструментов, чтобы добавить {nodes}.@@',
    '(new)' => '(новый)',
    'Active' => 'Активный',
    'Add new' => 'Добавить новый',
    'Add new root' => 'Добавить новый в корень',
    'Admin Settings' => 'Настройки администратора',
    'Already at bottom-most {node} in the hierarchy.' => '{node} уже находится в самом низу иерархии',
    'Already at left-most {node} in the hierarchy.' => '{node} уже находится на самом верхнем уровне иерархии',
    'Already at right-most {node} in the hierarchy.' => '{node} уже находится в самом последнем уровне иерархии',
    'Already at top-most {node} in the hierarchy.' => '{node} уже находится в самом верху иерархии',
    'Are you sure you want to remove this {node}?' => 'Вы действительно хотите удалить {node}?',
    'Cannot move this {node} as the {node} details are not saved yet.' => 'Нельзя переместить {node} пока вы его не сохранили',
    'Child Allowed' => 'Дочерние элементы разрешены',
    'Clear search results' => 'Очистить результаты поиска',
    'Collapsed' => 'Свернутый',
    'Default' => 'По умолчанию',
    'Delete' => 'Удалить',
    'Depth' => 'Глубина',
    'Disabled' => 'Выключенный',
    'Error removing the {node}. Please try again later.' => 'Ошибка перемещения {node}. Пожалуйста попробуйте позже.',
    'Error while creating the {node}. Please try again later.' => 'Ошибка при создании {node}. Пожалуйста, повторите попытку позже.',
    'Error while moving the {node}. Please try again later.' => 'Ошибка при перемещении {node}. Пожалуйста, повторите попытку позже.',
    'Error while removing the {node}. Please try again later.' => 'Ошибка при удалении {node}. Пожалуйста, повторите попытку позже.',
    'Error while saving the {node}. Please try again later.' => 'Ошибка при сохранении узел. Пожалуйста, повторите попытку позже.',
    'Error while viewing the {node}. Please try again later.' => 'Ошибка при просмотре {node}. Пожалуйста, повторите попытку позже.',
    'ID' => 'ИД',
    'Icon' => 'Иконка',
    'Icon Type' => 'Тип иконки',
    'Left' => 'Влево',
    'Movable Down' => 'Перемещаемый вниз',
    'Movable Left' => 'Перемещаемый влево',
    'Movable Right' => 'Перемещаемый вправо',
    'Movable Up' => 'Перемещаемый вверх',
    'Move Down' => 'Переместить вниз',
    'Move Left' => 'Переместить влево',
    'Move Right' => 'Переместить вправо',
    'Move Up' => 'Переместить вверх',
    'Name' => 'Название',
    'Read Only' => 'Только чтение',
    'Refresh' => 'Обновить',
    'Removable' => 'Удаляемый',
    'Removable (with children)' => 'Удаляемый (вместе с дочерними элементами)',
    'Reset' => 'Сбросить',
    'Right' => 'Вправо',
    'Root' => 'Корень',
    'Save' => 'Сохранить',
    'Saved the {node} details successfully.' => 'Данные {node} успешно сохранены',
    'Search...' => 'Поиск...',
    'Select a {node} by clicking on one of the tree items.' => 'Выберите {node}, нажав на один из дерева.',
    'Select...' => 'Выбрать...',
    'Selected' => 'Выбираемый',
    'The selected {node} cannot be moved.' => 'Этот выделенный {node} нельзя перенести.',
    'The untitled {node} was removed.' => '{node}ы без названия были удалены',
    'The {node} was moved successfully.' => '{node} успешно перемещен.',
    'The {node} was removed successfully.' => '{node} успешно удален.',
    'The {node} was successfully created.' => '{node} успешно создан.',
    'This operation is not allowed.' => 'Операция не разрешена',
    'Untitled' => 'Без названия',
    'Visible' => 'Видимый',
    'node' => 'Элемент',
    'nodes' => 'Элементов',
    '{node} # {id} - \'{name}\': {error}' => '{node} № {id} - \'{name}\': {error}',
];
