<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(new)' => '(nuovo)',
    'Active' => 'Attivo',
    'Add new' => 'Aggiungi nuovo',
    'Add new root' => 'Aggiungi nuova radice',
    'Admin Settings' => 'Modalità Admin',
    'Already at bottom-most node in the hierarchy.' => 'Nodo già in fondo alla gerarchia.',
    'Already at left-most node in the hierarchy.' => 'Nodo già al margine sinistro della gerarchia.',
    'Already at right-most node in the hierarchy.' => 'Nodo già al margine destro della gerarchia.',
    'Already at top-most node in the hierarchy.' => 'Nodo già in cima alla gerarchia',
    'Are you sure you want to remove this node?' => 'Confermi la rimozione del nodo?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Il nodo non può essere creato, Il nodo padre non è stato salvato o non è valido.',
    'Cannot move this node as the node details are not saved yet.' => 'Il nodo non può essere spostato perché i suoi dettagli non sono stati ancora salvati.',
    'Clear search results' => 'Annulla i risultati della ricerca',
    'Collapsed' => 'Chiuso',
    'Default' => 'Default',
    'Delete' => 'Cancella',
    'Depth' => 'Profondità',
    'Disabled' => 'Disabilitato',
    'Error while creating the node. Please try again later.' => 'Errore durante la creazione del nodo. Ritentare in seguito.',
    'Error while moving the node. Please try again later.' => 'Errore durante lo spostamento del nodo. Ritentare in seguito.',
    'Error while removing the node. Please try again later.' => 'Errore durante la rimozione del nodo. Ritentare in seguito.',
    'Error while saving the node. Please try again later.' => 'Errore durante il salvataggio del nodo. Ritentare in seguito.',
    'Error while viewing the node. Please try again later.' => 'Errore durante la visualizzazione del nodo. Ritentare in seguito.',
    'ID' => 'ID',
    'Icon' => 'Icona',
    'Icon Type' => ' Tipo icona',
    'Left' => 'Sinistra',
    'Movable Down' => 'Spostabile in Basso',
    'Movable Left' => 'Spostabile a Sinistra ',
    'Movable Right' => 'Spostabile a Destra ',
    'Movable Up' => 'Spostabile in Alto',
    'Move Down' => 'Sposta in Basso',
    'Move Left' => 'Sposta a Sinistra',
    'Move Right' => 'Sposta a Destra',
    'Move Up' => 'Sposta in Alto',
    'Name' => 'Nome',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Non ci sono nodi disponibili da mostrare. Utilizzare la i bottoni della toolbar per aggiungere nodi all\'albero',
    'Node # {id} - \'{name}\': {error}' => 'Nodo # {id} - \'{name}\': {error}',
    'Read Only' => 'Sola Lettura',
    'Refresh' => 'Aggiorna',
    'Removable' => 'Rimuovibile',
    'Removable (with children)' => 'Rimuovibile (con figli)',
    'Reset' => 'Annulla',
    'Right' => 'Destra',
    'Root' => 'Radice',
    'Save' => 'Salva',
    'Saved the node details successfully.' => 'Dettagli del nodo salvati con successo.',
    'Search...' => 'Cerca...',
    'Select a node by clicking on one of the tree items.' => 'Selezionare un nodo cliccando su un elemnto dell\'albero',
    'Select...' => 'Seleziona...',
    'Selected' => 'Selezionato',
    'The node was moved successfully.' => 'Nodo spostato con successo',
    'The node was removed successfully.' => 'Nodo rimosso con successo',
    'The node was successfully created.' => 'Nodo creato con successo.',
    'The untitled node was removed.' => 'Il nodo senza titolo è stato rimosso.',
    'This operation is not allowed.' => 'Operazione non permessa.',
    'Untitled' => 'Senza titolo',
    'Visible' => 'Visibile',
];
