<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error removing the node. Please try again later.' => '',
    'The selected node cannot be moved.' => '',
    '(new)' => '(новый)',
    'Active' => 'Активный',
    'Add new' => 'Добавить новый',
    'Add new root' => 'Добавить новый в корень',
    'Admin Settings' => 'Настройки администратора',
    'Already at bottom-most node in the hierarchy.' => 'Элемент уже находится в самом низу иерархии',
    'Already at left-most node in the hierarchy.' => 'Элемент уже находится на самом верхнем уровне иерархии',
    'Already at right-most node in the hierarchy.' => 'Элемент уже находится в самой последнем уровне иерархии',
    'Already at top-most node in the hierarchy.' => 'Элемент уже находится в самом вверху иерархии',
    'Are you sure you want to remove this node?' => 'Вы действительно хотите удалить элемент?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Нельзя создать элемент. Родительский элемент не сохранен',
    'Cannot move this node as the node details are not saved yet.' => 'Нельзя переместить элемент пока вы его не сохранили',
    'Clear search results' => 'Очистить результаты поиска',
    'Collapsed' => 'Свернутый',
    'Default' => 'По умолчанию',
    'Delete' => 'Удалить',
    'Depth' => 'Глубина',
    'Disabled' => 'Выключенный',
    'Error while creating the node. Please try again later.' => 'Ошибка при создании узла. Пожалуйста, повторите попытку позже.',
    'Error while moving the node. Please try again later.' => 'Ошибка при перемещении узла. Пожалуйста, повторите попытку позже.',
    'Error while removing the node. Please try again later.' => 'Ошибка при удалении узла. Пожалуйста, повторите попытку позже.',
    'Error while saving the node. Please try again later.' => 'Ошибка при сохранении узел. Пожалуйста, повторите попытку позже.',
    'Error while viewing the node. Please try again later.' => 'Ошибка при просмотре узла. Пожалуйста, повторите попытку позже.',
    'ID' => 'ИД',
    'Icon' => 'Иконка',
    'Icon Type' => 'Тип иконки',
    'Left' => 'Влево',
    'Movable Down' => 'Перемещаемый вниз',
    'Movable Left' => 'Перемещаемый влево',
    'Movable Right' => 'Перемещаемый вправо',
    'Movable Up' => 'Перемещаемый вверх',
    'Move Down' => 'Переместить вниз',
    'Move Left' => 'Переместить влево',
    'Move Right' => 'Переместить вправо',
    'Move Up' => 'Переместить вверх',
    'Name' => 'Название',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Нет доступных элементов дерева для отображения. Используйте кнопки на панели инструментов, чтобы добавить элементы.',
    'Node # {id} - \'{name}\': {error}' => 'Элемент № {id} - \'{name}\': {error}',
    'Read Only' => 'Только чтение',
    'Refresh' => 'Обновить',
    'Removable' => 'Удаляемый',
    'Removable (with children)' => 'Удаляемый (вместе с дочерними элементами)',
    'Reset' => 'Сбросить',
    'Right' => 'Вправо',
    'Root' => 'Корень',
    'Save' => 'Сохранить',
    'Saved the node details successfully.' => 'Данные элемента успешно сохранены',
    'Search...' => 'Поиск...',
    'Select a node by clicking on one of the tree items.' => 'Выберите элемент, нажав на один из дерева.',
    'Select...' => 'Выбрать...',
    'Selected' => 'Выбираемый',
    'The node was moved successfully.' => 'Элемент успешно перемещен.',
    'The node was removed successfully.' => 'Элемент успешно удален.',
    'The node was successfully created.' => 'Элемент успешно создан.',
    'The untitled node was removed.' => 'Элементы без названия были удалены',
    'This operation is not allowed.' => 'Операция не разрешена',
    'Untitled' => 'Без названия',
    'Visible' => 'Видимый',
];
