<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(new)' => '(nouveau)',
    'Active' => 'Actif',
    'Add new' => 'Ajouter',
    'Add new root' => 'Ajouter une racine',
    'Admin Settings' => 'Paramètres administrateur',
    'Already at bottom-most node in the hierarchy.' => 'Déjà au plus bas de l\'arborescence',
    'Already at left-most node in the hierarchy.' => 'Déjà eu plus à gauche de l\'arborescence',
    'Already at right-most node in the hierarchy.' => 'Déjà au plus à droite de l\'arborescence',
    'Already at top-most node in the hierarchy.' => 'Déjà au plus haut de l\'arborescence',
    'Are you sure you want to remove this node?' => 'Êtes-vous sûr de vouloir supprimer ce noeud ?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Impossible de créer le noeud. Le noeud parent n\'est pas enregistré ou invalide',
    'Cannot move this node as the node details are not saved yet.' => 'Impossible de déplacer ce noeud car les informations du noeud ne sont pas enregistrées.',
    'Clear search results' => 'Vider les résultats de recherche',
    'Collapsed' => 'Replié',
    'Default' => 'Défaut',
    'Delete' => 'Supprimer',
    'Depth' => 'Profondeur',
    'Disabled' => 'Désactivé',
    'Error removing the node. Please try again later.' => 'Erreur à la suppression du noeud. Réessayez plus tard.',
    'Error while creating the node. Please try again later.' => 'Erreur à la création du noeud. Réessayez plus tard.',
    'Error while moving the node. Please try again later.' => 'Erreur à la création du noeud. Réessayez plus tard.',
    'Error while removing the node. Please try again later.' => 'Erreur à la suppression du noeud. Réessayez plus tard.',
    'Error while saving the node. Please try again later.' => 'Erreur à l\'enregistrement du noeud. Réessayez plus tard.',
    'Error while viewing the node. Please try again later.' => 'Erreur à la visualisation du noeud. Réessayez plus tard.',
    'ID' => 'ID',
    'Icon' => 'Icône',
    'Icon Type' => 'Type d\'icône',
    'Left' => 'Gauche',
    'Movable Down' => 'Déplaçable vers le bas',
    'Movable Left' => 'Déplaçable vers la gauche',
    'Movable Right' => 'Déplaçable vers la droite',
    'Movable Up' => 'Déplaçable vers le haut',
    'Move Down' => 'Déplacer vers le bas',
    'Move Left' => 'Déplacer vers la gauche',
    'Move Right' => 'Déplacer vers la droite',
    'Move Up' => 'Déplacer vers le haut',
    'Name' => 'Nom',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Aucun noeud d\'arborescence disponible. Utilisez les boutons pour ajouter un noeud.',
    'Node # {id} - \'{name}\': {error}' => 'Noeud # {id} - \'{name}\' : {error}',
    'Read Only' => 'Lecture seule',
    'Refresh' => 'Rafraîchir',
    'Removable' => 'Supprimable',
    'Removable (with children)' => 'Supprimable (avec enfants)',
    'Reset' => 'Réinitialiser',
    'Right' => 'Droite',
    'Root' => 'Racine',
    'Save' => 'Enregistrer',
    'Saved the node details successfully.' => 'Enregistrement réussi des informations du noeud.',
    'Search...' => 'Rechercher...',
    'Select a node by clicking on one of the tree items.' => 'Sélectionner un noeud en cliquant sur l\'un des items de l\'arborescence',
    'Select...' => 'Sélectionner...',
    'Selected' => 'Sélectionné',
    'The node was moved successfully.' => 'Le noeud a été déplacé avec succès.',
    'The node was removed successfully.' => 'Le noeud a été supprimé avec succès.',
    'The node was successfully created.' => 'Le noeud a été créé avec succès.',
    'The selected node cannot be moved.' => 'Le noeud sélectionné ne peut pas être déplacé.',
    'The untitled node was removed.' => 'Le noeud sans titre a été déplacé.',
    'This operation is not allowed.' => 'L\'opération n\'est pas autorisée',
    'Untitled' => 'Sans titre',
    'Visible' => 'Visible',
];
