<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    'Cannot create {node}. Parent node is not saved or is invalid.' => '',
    'Cannot move root level {nodes} before or after other root level {nodes}.' => '',
    'Child Allowed' => '',
    'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => '',
    'You cannot add children under this {node}.' => '',
    'Cannot create {node}. Parent {node} is not saved or is invalid.' => '@@{node} luonti epäonnistui. Ylemmän tason kohdetta ei ole tallennettu tai ei kelpaa@@',
    'No valid tree {nodes} are available for display. Use toolbar buttons to add tree {nodes}.' => '@@Ei näytettäviä {nodes}. Käytä työkalurivin nappeja luodaksesi uusia {nodes}@@',
    '(new)' => '(uusi)',
    'Active' => 'Aktiivinen',
    'Add new' => 'Lisää uusi',
    'Add new root' => 'Lisää uusi alapolku',
    'Admin Settings' => 'Ylläpidon asetukset',
    'Already at bottom-most {node} in the hierarchy.' => '{node} on jo hierarkkian alimmaisena',
    'Already at left-most {node} in the hierarchy.' => '{node} on jo hierarkkian vasemmanpuoleisimpana',
    'Already at right-most {node} in the hierarchy.' => '{node} on jo hierarkkian oikeanpuoleisimpana',
    'Already at top-most {node} in the hierarchy.' => '{node} on jo hierarkkian ylimpänä',
    'Are you sure you want to remove this {node}?' => 'Oletko varma, että haluat poistaa {node}?',
    'Cannot move this {node} as the {node} details are not saved yet.' => '{node}a ei voi siirtää, koska sen tietoja ei ole vielä tallennettu',
    'Clear search results' => 'Pyyhi hakutulokset',
    'Collapsed' => 'Pienennetty',
    'Default' => 'Oletus',
    'Delete' => 'Poista',
    'Depth' => 'Taso',
    'Disabled' => 'Estetty',
    'Error removing the {node}. Please try again later.' => 'Virhe {node} poistossa. Yritä myöhemmin uudelleen.',
    'Error while creating the {node}. Please try again later.' => 'Virhe {node} luonnissa. Yritä myöhemmin uudelleen.',
    'Error while moving the {node}. Please try again later.' => 'Virhe {node} siirrossa. Yritä myöhemmin uudelleen.',
    'Error while removing the {node}. Please try again later.' => 'Virhe {node} poistossa. Yritä myöhemmin uudelleen.',
    'Error while saving the {node}. Please try again later.' => 'Virhe {node} tallennuksessa. Yritä myöhemmin uudelleen.',
    'Error while viewing the {node}. Please try again later.' => 'Virhe {node} tarkastelussa. Yritä myöhemmin uudelleen.',
    'ID' => 'Tunnus',
    'Icon' => 'Ikoni',
    'Icon Type' => 'Ikonin tyyppi',
    'Left' => 'Vasen',
    'Movable Down' => 'Siirrettävissä alas',
    'Movable Left' => 'Siirrettävissä vasemmalle',
    'Movable Right' => 'Siirrettävissä oikealle',
    'Movable Up' => 'Siirrettävissä ylös',
    'Move Down' => 'Liikuta alas',
    'Move Left' => 'Liikuta vasemmalle',
    'Move Right' => 'Liikuta oikealle',
    'Move Up' => 'Liikuta ylös',
    'Name' => 'Nimi',
    'Read Only' => 'Vain lukukelpoinen',
    'Refresh' => 'Päivitä',
    'Removable' => 'Poistettavissa',
    'Removable (with children)' => 'Poistettavissa (alakohtineen)',
    'Reset' => 'Palauta alkuperäiseen',
    'Right' => 'Oikea',
    'Root' => 'Alapolku',
    'Save' => 'Tallenna',
    'Saved the {node} details successfully.' => 'Kohteen tiedot on tallennettu.',
    'Search...' => 'Etsi...',
    'Select a {node} by clicking on one of the tree items.' => 'Valitse haluamasi {node} klikkaamalla yhtä puun kohdista.',
    'Select...' => 'Valitse...',
    'Selected' => 'Valittu',
    'The selected {node} cannot be moved.' => 'Valittua {node} ei voida siirtää',
    'The untitled {node} was removed.' => 'Nimeämätön {node} poistettiin',
    'The {node} was moved successfully.' => '{node} siirto onnistui',
    'The {node} was removed successfully.' => '{node} poisto onnistui',
    'The {node} was successfully created.' => '{node} luonti onnistui',
    'This operation is not allowed.' => 'Operaatio ei ole sallittu',
    'Untitled' => 'Nimeämätön',
    'Visible' => 'Näkyvissä',
    'node' => 'kohdan',
    'nodes' => 'kohtia',
    '{node} # {id} - \'{name}\': {error}' => '{node} #{id} - \'{name}\': {error}',
];
