<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error removing the node. Please try again later.' => '',
    'The selected node cannot be moved.' => '',
    '(new)' => '(Neu)',
    'Active' => 'Aktiv',
    'Add new' => 'Neuer Eintrag',
    'Add new root' => 'Neuer Root Eintrag',
    'Admin Settings' => 'Administrator Einstellungen',
    'Already at bottom-most node in the hierarchy.' => 'Bereits am letzten Eintrag',
    'Already at left-most node in the hierarchy.' => 'Bereits am höchsten Eintrag',
    'Already at right-most node in the hierarchy.' => 'Bereits am tiefsten Eintrag',
    'Already at top-most node in the hierarchy.' => 'Bereits am obersten Eintrag',
    'Are you sure you want to remove this node?' => 'Wollen Sie diesen Eintrag wirklich löschen?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Eintrag konnte nicht erstellt werden. Elterneintrag nicht gespeichert oder ungültig.',
    'Cannot move this node as the node details are not saved yet.' => 'Eintrag konnte nicht verschoben werden, da die Details noch nicht gespeichert wurden.',
    'Clear search results' => 'Suchergebnis verwerfen',
    'Collapsed' => 'Eingeklappt',
    'Default' => 'Standart',
    'Delete' => 'Löschen',
    'Depth' => 'Tiefe',
    'Disabled' => 'Deaktiviert',
    'Error while creating the node. Please try again later.' => 'Fehler beim Erstellen des Knotens. Bitte versuchen Sie es später noch einmal.',
    'Error while moving the node. Please try again later.' => 'Fehler beim Verschieben des Knotens. Bitte versuchen Sie es später noch einmal.',
    'Error while removing the node. Please try again later.' => 'Fehler beim Entfernen des Knotens. Bitte versuchen Sie es später noch einmal.',
    'Error while saving the node. Please try again later.' => 'Fehler beim Speichern der Knoten. Bitte versuchen Sie es später noch einmal.',
    'Error while viewing the node. Please try again later.' => 'Fehler beim Anzeigen der Knoten. Bitte versuchen Sie es später noch einmal.',
    'ID' => 'ID',
    'Icon' => 'Icon',
    'Icon Type' => 'Icon Typ',
    'Left' => 'Links',
    'Movable Down' => 'Nach unten verschiebbar',
    'Movable Left' => 'Nach links verschiebbar',
    'Movable Right' => 'Nach rechts verschiebbar',
    'Movable Up' => 'Nach oben verschiebbar',
    'Move Down' => 'Nach unten schieben',
    'Move Left' => 'Nach links schieben',
    'Move Right' => 'Nach rechts schieben',
    'Move Up' => 'Nach oben schieben',
    'Name' => 'Name',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Keine Einträge für die Anzeige. Fügen Sie neue über die Toolbar ein.',
    'Node # {id} - \'{name}\': {error}' => 'Eintrag # {id} - \'{name}\': {error}',
    'Read Only' => 'Nur lesen',
    'Refresh' => 'Neu laden',
    'Removable' => 'Löschbar',
    'Removable (with children)' => 'Löschbar (mit enthaltenen Einträgen)',
    'Reset' => 'Zurücksetzen',
    'Right' => 'Rechts',
    'Root' => 'Stamm',
    'Save' => 'Speichern',
    'Saved the node details successfully.' => 'Eintragdetails erfolgreich gespeichert.',
    'Search...' => 'Suchen...',
    'Select a node by clicking on one of the tree items.' => 'Wähle einen der drei Einträge durch klicken. ',
    'Select...' => 'Auswahl...',
    'Selected' => 'Ausgewählt',
    'The node was moved successfully.' => 'Der Eintrag wurde erfolgreich verschoben.',
    'The node was removed successfully.' => 'Der Eintrag wurde erfolgreich gelöscht.',
    'The node was successfully created.' => 'Der Eintrag wurde erfolgreich erstellt.',
    'The untitled node was removed.' => 'Der unbenannte Eintrag wurde erfolgreich gelöscht.',
    'This operation is not allowed.' => 'Aktion ist nicht erlaubt.',
    'Untitled' => 'Unbenannt',
    'Visible' => 'Sichtbar',
];
