<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    'Cannot create {node}. Parent node is not saved or is invalid.' => '',
    'Cannot move root level {nodes} before or after other root level {nodes}.' => '',
    'Child Allowed' => '',
    'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => '',
    'You cannot add children under this {node}.' => '',
    'Cannot create {node}. Parent {node} is not saved or is invalid.' => '@@Il {node} non può essere creato, Il {node} padre non è stato salvato o non è valido.@@',
    'No valid tree {nodes} are available for display. Use toolbar buttons to add tree {nodes}.' => '@@Non ci sono {nodes} disponibili da mostrare. Utilizzare i bottoni della toolbar per aggiungere {nodes} all\'albero@@',
    '(new)' => '(nuovo)',
    'Active' => 'Attivo',
    'Add new' => 'Aggiungi nuovo',
    'Add new root' => 'Aggiungi nuova radice',
    'Admin Settings' => 'Modalità Admin',
    'Already at bottom-most {node} in the hierarchy.' => '{node} già in fondo alla gerarchia.',
    'Already at left-most {node} in the hierarchy.' => '{node} già al margine sinistro della gerarchia.',
    'Already at right-most {node} in the hierarchy.' => '{node} già al margine destro della gerarchia.',
    'Already at top-most {node} in the hierarchy.' => '{node} già in cima alla gerarchia',
    'Are you sure you want to remove this {node}?' => 'Confermi la rimozione del {node}?',
    'Cannot move this {node} as the {node} details are not saved yet.' => 'Il {node} non può essere spostato perché i suoi dettagli non sono stati ancora salvati.',
    'Clear search results' => 'Annulla i risultati della ricerca',
    'Collapsed' => 'Chiuso',
    'Default' => 'Default',
    'Delete' => 'Cancella',
    'Depth' => 'Profondità',
    'Disabled' => 'Disabilitato',
    'Error removing the {node}. Please try again later.' => 'Errore durante la rimozione del {node}. Riprovare più tardi.',
    'Error while creating the {node}. Please try again later.' => 'Errore durante la creazione del {node}. Ritentare in seguito.',
    'Error while moving the {node}. Please try again later.' => 'Errore durante lo spostamento del {node}. Ritentare in seguito.',
    'Error while removing the {node}. Please try again later.' => 'Errore durante la rimozione del {node}. Ritentare in seguito.',
    'Error while saving the {node}. Please try again later.' => 'Errore durante il salvataggio del {node}. Ritentare in seguito.',
    'Error while viewing the {node}. Please try again later.' => 'Errore durante la visualizzazione del {node}. Ritentare in seguito.',
    'ID' => 'ID',
    'Icon' => 'Icona',
    'Icon Type' => ' Tipo icona',
    'Left' => 'Sinistra',
    'Movable Down' => 'Spostabile in Basso',
    'Movable Left' => 'Spostabile a Sinistra ',
    'Movable Right' => 'Spostabile a Destra ',
    'Movable Up' => 'Spostabile in Alto',
    'Move Down' => 'Sposta in Basso',
    'Move Left' => 'Sposta a Sinistra',
    'Move Right' => 'Sposta a Destra',
    'Move Up' => 'Sposta in Alto',
    'Name' => 'Nome',
    'Read Only' => 'Sola Lettura',
    'Refresh' => 'Aggiorna',
    'Removable' => 'Rimuovibile',
    'Removable (with children)' => 'Rimuovibile (con figli)',
    'Reset' => 'Annulla',
    'Right' => 'Destra',
    'Root' => 'Radice',
    'Save' => 'Salva',
    'Saved the {node} details successfully.' => 'Dettagli del {node} salvati con successo.',
    'Search...' => 'Cerca...',
    'Select a {node} by clicking on one of the tree items.' => 'Selezionare un {node} cliccando su un elemento dell\'albero',
    'Select...' => 'Seleziona...',
    'Selected' => 'Selezionato',
    'The selected {node} cannot be moved.' => 'Il {node} selezionato non può essere spostato',
    'The untitled {node} was removed.' => 'Il {node} senza titolo è stato rimosso.',
    'The {node} was moved successfully.' => '{node} spostato con successo',
    'The {node} was removed successfully.' => '{node} rimosso con successo',
    'The {node} was successfully created.' => '{node} creato con successo.',
    'This operation is not allowed.' => 'Operazione non permessa.',
    'Untitled' => 'Senza titolo',
    'Visible' => 'Visibile',
    'node' => 'nodo',
    'nodes' => 'nodi',
    '{node} # {id} - \'{name}\': {error}' => '{node} # {id} - \'{name}\': {error}',
];
