<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error removing the node. Please try again later.' => '',
    'The selected node cannot be moved.' => '',
    '(new)' => '(новий)',
    'Active' => 'Активний',
    'Add new' => 'Додати новий',
    'Add new root' => 'Додати новий у корінь',
    'Admin Settings' => 'Налаштування адміністратора',
    'Already at bottom-most node in the hierarchy.' => 'Елемент вже знаходиться в самому низу ієрархії',
    'Already at left-most node in the hierarchy.' => 'Елемент вже знаходиться на самому верхньому рівні ієрархії',
    'Already at right-most node in the hierarchy.' => 'Елемент вже знаходиться в самій останньому рівні ієрархії',
    'Already at top-most node in the hierarchy.' => 'Елемент вже знаходиться в самому верху ієрархії',
    'Are you sure you want to remove this node?' => 'Ви дійсно хочете видалити елемент?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Не можна створити елемент. Батьківський елемент не збережено',
    'Cannot move this node as the node details are not saved yet.' => 'Не можна перемістити елемент поки ви його не зберегли',
    'Clear search results' => 'Очистити результати пошуку',
    'Collapsed' => 'Згорнутий',
    'Default' => 'За замовчуванням',
    'Delete' => 'Видалити',
    'Depth' => 'Глибина',
    'Disabled' => 'Виключений',
    'Error while creating the node. Please try again later.' => 'Помилка при створенні вузла. Будь ласка, спробуйте пізніше.',
    'Error while moving the node. Please try again later.' => 'Помилка при переміщенні вузла. Будь ласка, спробуйте пізніше.',
    'Error while removing the node. Please try again later.' => 'Помилка при видаленні вузла. Будь ласка, спробуйте пізніше.',
    'Error while saving the node. Please try again later.' => 'Помилка при збереженні вузла. Будь ласка, спробуйте пізніше.',
    'Error while viewing the node. Please try again later.' => 'Помилка при перегляді вузла. Будь ласка, спробуйте пізніше.',
    'ID' => 'ІД',
    'Icon' => 'Іконка',
    'Icon Type' => 'Тип іконки',
    'Left' => 'Вліво',
    'Movable Down' => 'Переміщуваний вниз',
    'Movable Left' => 'Переміщуваний вліво',
    'Movable Right' => 'Переміщуваний вправо',
    'Movable Up' => 'Переміщуваний вверх',
    'Move Down' => 'Перемістити вниз',
    'Move Left' => 'Перемістити вліво',
    'Move Right' => 'Перемістити вправо',
    'Move Up' => 'Перемістити вгору',
    'Name' => 'Назва',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Немає доступних елементів дерева для відображення. Використовуйте кнопки на панелі інструментів, щоб додати елементи.',
    'Node # {id} - \'{name}\': {error}' => 'Елемент № {id} - \'{name}\': {error}',
    'Read Only' => 'Тільки читання',
    'Refresh' => 'Оновити',
    'Removable' => 'Вдаляємий',
    'Removable (with children)' => 'Видаляємий (разом з дочірніми елементами)',
    'Reset' => 'Скинути',
    'Right' => 'Вправо',
    'Root' => 'Корінь',
    'Save' => 'Зберегти',
    'Saved the node details successfully.' => 'Дані елемента успішно збережені',
    'Search...' => 'Пошук...',
    'Select a node by clicking on one of the tree items.' => 'Виберіть елемент, натиснувши на один з дерева.',
    'Select...' => 'Вибрати...',
    'Selected' => 'Обираємий',
    'The node was moved successfully.' => 'Елемент успішно переміщений.',
    'The node was removed successfully.' => 'Елемент успішно видалений.',
    'The node was successfully created.' => 'Елемент успішно створений.',
    'The untitled node was removed.' => 'Елементи без назви були видалені',
    'This operation is not allowed.' => 'Операція не дозволена',
    'Untitled' => 'Без назви',
    'Visible' => 'Видимий',
];
