<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'(new)' => '(جدید)',
	'Active' => 'فعال',
	'Add new' => 'ایجاد',
	'Add new root' => 'ایجاد سرشاخه',
	'Admin Settings' => 'تنظیمات مدیر',
	'Already at bottom-most node in the hierarchy.' => 'این نود در پایین ترین نقطه ممکن قرار دارد.',
	'Already at left-most node in the hierarchy.' => 'این نود در چپ ترین نقطه ممکن قرار دارد.',
	'Already at right-most node in the hierarchy.' => 'این نود در راست ترین نقطه ممکن قرار دارد.',
	'Already at top-most node in the hierarchy.' => 'این نود در بالا ترین نقطه ممکن قرار دارد.',
	'Are you sure you want to remove this node?' => 'آیا از حذف این نود مطمئن هستید؟',
	'Cannot create node. Parent node is not saved or is invalid.' => 'امکان ایجاد نود وجود ندارد. نود والد ذخیره نشده یا معتبر نیست.',
	'Cannot move this node as the node details are not saved yet.' => 'امکان جابجایی نود بدلیل ذخیره نکردن تغییرات وجود ندارد.',
	'Clear search results' => 'پاک کردن سابقه جستجو',
	'Collapsed' => 'بسته شده',
	'Default' => 'پیش فرض',
	'Delete' => 'حذف',
	'Depth' => 'عمق',
	'Disabled' => 'غیرفعال',
	'Error removing the node. Please try again later.' => 'خطا در حذف نود. لطفا دوباره سعی کنید.',
	'Error while creating the node. Please try again later.' => 'خطا در ایجاد نود. لطفا دوباره سعی کنید.',
	'Error while moving the node. Please try again later.' => 'خطا در جابجایی نود. لطفا دوباره سعی کنید.',
	'Error while removing the node. Please try again later.' => 'خطا در حذف نود. لطفا دوباره سعی کنید.',
	'Error while saving the node. Please try again later.' => 'خطا در ذخیره نود. لطفا دوباره سعی کنید.',
	'Error while viewing the node. Please try again later.' => 'خطا در نمایش نود. لطفا دوباره سعی کنید.',
	'ID' => 'کد',
	'Icon' => 'آیکون',
	'Icon Type' => 'نوع آیکون',
	'Left' => 'چپ',
	'Movable Down' => 'جابجا شونده به پایین',
	'Movable Left' => 'جابجا شونده به چپ',
	'Movable Right' => 'جابجا شونده به راست',
	'Movable Up' => 'جابجا شونده به بالا',
	'Move Down' => 'جابجا به پایین',
	'Move Left' => 'جابجا به چپ',
	'Move Right' => 'جابجا به راست',
	'Move Up' => 'جابجا به بالا',
	'Name' => 'عنوان',
	'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'جهت نمایش اطلاعات، یک نود را انتخاب کنید.',
	'Node # {id} - \'{name}\': {error}' => 'نود {id} - \'{name}\': {error}',
	'Read Only' => 'فقط خواندنی',
	'Refresh' => 'بازنمایی',
	'Removable' => 'قابل حذف',
	'Removable (with children)' => 'قابل حذف (با تمام زیرشاخه)',
	'Reset' => 'بازنشاندن',
	'Right' => 'راست',
	'Root' => 'سرشاخه',
	'Save' => 'ذخیره',
	'Saved the node details successfully.' => 'مشخصات با موفقیت ذخیره شد.',
	'Search...' => 'جستجو...',
	'Select a node by clicking on one of the tree items.' => 'با کلیک بر روی یک نود، آن را انتخاب کنید.',
	'Select...' => 'انتخاب...',
	'Selected' => 'انتخاب شده',
	'The node was moved successfully.' => 'نود با موفقیت جابجا شد.',
	'The node was removed successfully.' => 'نود با موفقیت حذف شد.',
	'The node was successfully created.' => 'نود با موفقیت ایجاد شد.',
	'The selected node cannot be moved.' => 'امکان جابجایی نود انخاب شده وجود ندارد.',
	'The untitled node was removed.' => 'نود بدون نام با موفقیت حذف شد.',
	'This operation is not allowed.' => 'امکان انجام این کار وجود ندارد.',
	'Untitled' => 'بدون نام',
	'Visible' => 'دیدنی',
];
