<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Error removing the node. Please try again later.' => '',
    'The selected node cannot be moved.' => '',
    '(new)' => '(nowa)',
    'Active' => 'Aktywna',
    'Add new' => 'Dodaj nową',
    'Add new root' => 'Dodaj nową kategorię główną',
    'Admin Settings' => 'Opcje ustawień',
    'Already at bottom-most node in the hierarchy.' => 'Już na samym dole aktualnej kategorii.',
    'Already at left-most node in the hierarchy.' => 'Już na samym początku kategorii.',
    'Already at right-most node in the hierarchy.' => 'Już na samym końcu kategorii.',
    'Already at top-most node in the hierarchy.' => 'Już na samej górze aktualnej kategorii.',
    'Are you sure you want to remove this node?' => 'Czy na pewno chcesz usunąć tę pozycję?',
    'Cannot create node. Parent node is not saved or is invalid.' => 'Nie można dodać tej pozycji. Kategoria rodzica nie została zapisana lub jest nieprawidłowa.',
    'Cannot move this node as the node details are not saved yet.' => 'Nie można przesunąć tej pozycji, ponieważ jej opcje nie zostały jeszcze zapisane.',
    'Clear search results' => 'Wyczyść pole wyszukiwania',
    'Collapsed' => 'Zwinięta',
    'Default' => 'Domyślna',
    'Delete' => 'Usuń',
    'Depth' => 'Głębokość',
    'Disabled' => 'Nieaktywna',
    'Error while creating the node. Please try again later.' => 'Wystąpił błąd w czasie dodawania pozycji. Proszę spróbować ponownie za chwilę.',
    'Error while moving the node. Please try again later.' => 'Wystąpił błąd w czasie przenoszenia pozycji. Proszę spróbować ponownie za chwilę.',
    'Error while removing the node. Please try again later.' => 'Wystąpił błąd w czasie usuwania pozycji. Proszę spróbować ponownie za chwilę.',
    'Error while saving the node. Please try again later.' => 'Wystąpił błąd w czasie zapisywania pozycji. Proszę spróbować ponownie za chwilę.',
    'Error while viewing the node. Please try again later.' => 'Wystąpił błąd w czasie wyświetlania pozycji. Proszę spróbować ponownie za chwilę.',
    'ID' => 'ID',
    'Icon' => 'Ikona',
    'Icon Type' => 'Typ ikony',
    'Left' => 'Lewo',
    'Movable Down' => 'Przesuwalna w dół',
    'Movable Left' => 'Przesuwalna w lewo',
    'Movable Right' => 'Przesuwalna w prawo',
    'Movable Up' => 'Przesuwalna w górę',
    'Move Down' => 'Przenieś w dół',
    'Move Left' => 'Przenieś na lewo',
    'Move Right' => 'Przenieś na prawo',
    'Move Up' => 'Przenieś do góry',
    'Name' => 'Nazwa',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => 'Brak pozycji do wyświetlenia. Użyj przycisku na pasku narzędzi, aby dodać nową.',
    'Node # {id} - \'{name}\': {error}' => 'Pozycja # {id} - \'{name}\': {error}',
    'Read Only' => 'Tylko do odczytu',
    'Refresh' => 'Odśwież',
    'Removable' => 'Usuwalna',
    'Removable (with children)' => 'Usuwalna (wraz z podpozycjami)',
    'Reset' => 'Reset',
    'Right' => 'Prawo',
    'Root' => 'Start',
    'Save' => 'Zapis',
    'Saved the node details successfully.' => 'Opcje pozycji zostały poprawnie zapisane.',
    'Search...' => 'Wyszukaj...',
    'Select a node by clicking on one of the tree items.' => 'Wybierz pozycję klikając na jej nazwę na liście.',
    'Select...' => 'Wybierz...',
    'Selected' => 'Zaznaczona',
    'The node was moved successfully.' => 'Pozycja została poprawnie przeniesiona.',
    'The node was removed successfully.' => 'Pozycja została poprawnie usunięta.',
    'The node was successfully created.' => 'Pozycja została poprawnie dodana.',
    'The untitled node was removed.' => 'Nienazwana pozycja została usunięta.',
    'This operation is not allowed.' => 'Ta operacja nie jest dozwolona.',
    'Untitled' => 'Bez tytułu',
    'Visible' => 'Widoczna',
];
