<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(new)' => '',
    'Active' => '',
    'Add new' => '',
    'Add new root' => '',
    'Admin Settings' => '',
    'Already at bottom-most node in the hierarchy.' => '',
    'Already at left-most node in the hierarchy.' => '',
    'Already at right-most node in the hierarchy.' => '',
    'Already at top-most node in the hierarchy.' => '',
    'Are you sure you want to remove this node?' => '',
    'Cannot create node. Parent node is not saved or is invalid.' => '',
    'Cannot move this node as the node details are not saved yet.' => '',
    'Clear search results' => '',
    'Collapsed' => '',
    'Default' => '',
    'Delete' => '',
    'Depth' => '',
    'Disabled' => '',
    'Error removing the node. Please try again later.' => '',
    'Error while creating the node. Please try again later.' => '',
    'Error while moving the node. Please try again later.' => '',
    'Error while removing the node. Please try again later.' => '',
    'Error while saving the node. Please try again later.' => '',
    'Error while viewing the node. Please try again later.' => '',
    'ID' => '',
    'Icon' => '',
    'Icon Type' => '',
    'Left' => '',
    'Movable Down' => '',
    'Movable Left' => '',
    'Movable Right' => '',
    'Movable Up' => '',
    'Move Down' => '',
    'Move Left' => '',
    'Move Right' => '',
    'Move Up' => '',
    'Name' => '',
    'No valid tree nodes are available for display. Use toolbar buttons to add tree nodes.' => '',
    'Node # {id} - \'{name}\': {error}' => '',
    'Read Only' => '',
    'Refresh' => '',
    'Removable' => '',
    'Removable (with children)' => '',
    'Reset' => '',
    'Right' => '',
    'Root' => '',
    'Save' => '',
    'Saved the node details successfully.' => '',
    'Search...' => '',
    'Select a node by clicking on one of the tree items.' => '',
    'Select...' => '',
    'Selected' => '',
    'The node was moved successfully.' => '',
    'The node was removed successfully.' => '',
    'The node was successfully created.' => '',
    'The selected node cannot be moved.' => '',
    'The untitled node was removed.' => '',
    'This operation is not allowed.' => '',
    'Untitled' => '',
    'Visible' => '',
];
