<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<h4>Operation Disallowed</h4><hr>Invalid request signature detected during tree data <b>{action}</b> action! Please refresh the page and retry.{params}' => '',
    'Cannot create {node}. Parent node is not saved or is invalid.' => '',
    'Cannot move root level {nodes} before or after other root level {nodes}.' => '',
    'Child Allowed' => '',
    'Collapsed' => '',
    'Disabled' => '',
    'ID' => '',
    'No valid {nodes} are available for display. Use toolbar buttons to add {nodes}.' => '',
    'You cannot add children under this {node}.' => '',
    'nodes' => '',
    'Cannot create {node}. Parent {node} is not saved or is invalid.' => '@@Ei saa {node} lisada. Ülemus-{node} on salvestamata või vigane.@@',
    'No valid tree {nodes} are available for display. Use toolbar buttons to add tree {nodes}.' => '@@Ühtki puu {nodes} ei ole näitamiseks saadaval. Palun kasuta tööriba nuppe, et {nodes} lisada.@@',
    '(new)' => '(uus)',
    'Active' => 'Aktiivne',
    'Add new' => 'Lisa uus',
    'Add new root' => 'Lisa uus tüvi',
    'Admin Settings' => 'Administraatori seaded',
    'Already at bottom-most {node} in the hierarchy.' => 'Juba hierarhia kõige alumise {node} juures.',
    'Already at left-most {node} in the hierarchy.' => 'Juba hierarhia kõige vasakpoolsema {node} juures.',
    'Already at right-most {node} in the hierarchy.' => 'Juba hierarhia kõige parempoolsema {node} juures.',
    'Already at top-most {node} in the hierarchy.' => 'Juba hierarhia kõige ülemise {node} juures.',
    'Are you sure you want to remove this {node}?' => 'Oled sa kindel, et tahad selle {node} kustutada?',
    'Cannot move this {node} as the {node} details are not saved yet.' => 'Ei saa seda {node} liigutada, kuna {node} detailid ei ole veel salvestatud.',
    'Clear search results' => 'Puhasta otsingu tulemused',
    'Default' => 'Vaikimisi',
    'Delete' => 'Kustuta',
    'Depth' => 'Sügavus',
    'Error removing the {node}. Please try again later.' => 'Viga {node} kustutamisel. Palun proovi hiljem uuesti.',
    'Error while creating the {node}. Please try again later.' => 'Viga {node} loomisel. Palun proovi hiljem uuesti.',
    'Error while moving the {node}. Please try again later.' => 'Viga {node} liigutamisel. Palun proovi hiljem uuesti.',
    'Error while removing the {node}. Please try again later.' => 'Viga {node} kustutamisel. Palun proovi hiljem uuesti.',
    'Error while saving the {node}. Please try again later.' => 'Viga {node} salvestamisel. Palun proovi hiljem uuesti.',
    'Error while viewing the {node}. Please try again later.' => 'Viga {node} vaatamisel. Palun proovi hiljem uuesti.',
    'Icon' => 'Ikoon',
    'Icon Type' => 'Ikooni tüüp',
    'Left' => 'Vasak',
    'Movable Down' => 'Alla liigutatav',
    'Movable Left' => 'Vasakule liigutatav',
    'Movable Right' => 'Paremale liigutatav',
    'Movable Up' => 'Üles liigutatav',
    'Move Down' => 'Liigutata alla',
    'Move Left' => 'Liigutata vasakule',
    'Move Right' => 'Liigutata paremale',
    'Move Up' => 'Liigutata üles',
    'Name' => 'Nimi',
    'Read Only' => 'Ainult lugemiseks',
    'Refresh' => 'Värskenda',
    'Removable' => 'Eemaldatav',
    'Removable (with children)' => 'Eemaldatav (koos alam-elementidega)',
    'Reset' => 'Lähtesta',
    'Right' => 'Parem',
    'Root' => 'Tüvi',
    'Save' => 'Salvesta',
    'Saved the {node} details successfully.' => '{node} detailide salvestamine õnnestus.',
    'Search...' => 'Otsi...',
    'Select a {node} by clicking on one of the tree items.' => 'Valimiseks kliki mõnel puu {node}',
    'Select...' => 'Vali...',
    'Selected' => 'Valitud',
    'The selected {node} cannot be moved.' => 'Valitud {node} ei saa liigutada.',
    'The untitled {node} was removed.' => 'Ilma nimeta {node} kustutati.',
    'The {node} was moved successfully.' => '{node} liigutamine õnnestus.',
    'The {node} was removed successfully.' => '{node} kustutamine õnnestus.',
    'The {node} was successfully created.' => '{node} loomine õnnestus.',
    'This operation is not allowed.' => 'See toiming ei ole lubatud.',
    'Untitled' => 'Ilma nimeta',
    'Visible' => 'Nähtav',
    'node' => 'sõlmed',
    '{node} # {id} - \'{name}\': {error}' => '{node} # {id} - \'{name}\': {error}',
];
